# Generated by Django 3.2.8 on 2021-11-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.CharField(blank=True, max_length=55, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('form', models.CharField(max_length=255)),
                ('date', models.DateField(null=True)),
                ('sitting', models.PositiveIntegerField()),
                ('voting', models.PositiveIntegerField()),
                ('results', models.JSONField()),
            ],
            options={
                'db_table': 'votings',
                'ordering': ['-sitting', '-voting'],
            },
        ),
    ]
