# Generated by Django 3.2.8 on 2021-11-06 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('slug', models.SlugField()),
                ('date', models.DateTimeField()),
                ('image', models.JSONField()),
                ('author', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'News',
                'db_table': 'news',
                'ordering': ['-date'],
            },
        ),
    ]
