# Generated by Django 3.2.8 on 2021-11-06 11:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('electionDate', models.DateField()),
                ('list', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('votes', models.PositiveBigIntegerField()),
                ('pledge', models.DateField()),
                ('experience', models.CharField(max_length=255)),
                ('party', models.CharField(max_length=255)),
                ('dateOfBirth', models.CharField(max_length=255, null=True)),
                ('education', models.CharField(max_length=255, null=True)),
                ('school', models.CharField(max_length=255, null=True)),
                ('job', models.CharField(max_length=255, null=True)),
                ('photoUrl', models.URLField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Members',
                'db_table': 'members',
            },
        ),
    ]
